import { Toaster } from "sonner";
import "./globals.css";

export const metadata = {
  title: "Feedback App ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
